version: '3.8'
services:
  node-app:
    container_name: node-app
    restart: always
    build: ./node
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 --timeout 30s docker-entrypoint.sh
    command: sh -c "npm install && npm start"
    depends_on:
      - db
    volumes:
      - ./node:/home/node
    ports:
      - 3000:3000
    networks:
      - fc-app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fc-app

  nginx:
    container_name: reverse-proxy
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - fc-app

networks:
  fc-app:
    driver: bridge